### ISSUE TITLE
UUID column type not recognized

### ISSUE THREAD

**Issue by readytheory** [cockroachlabs/hello-world-python-psycopg2#10]
On commit [a7e5ba6](https://github.com/cockroachlabs/hello-world-python-psycopg2/commit/a7e5ba6af6b67f400aaa0477361df3846b2ab07f)

This change:

  ```
      cur.execute(
            "UPSERT INTO accounts (id, balance) VALUES (%s, 1000), (%s, 250)", (id1, id2))
```

raises ```psycopg2.errors.DatatypeMismatch: value type uuid doesn't match type int of column "id"```

psycopg2 is:  2.9.3 (dt dec pq3 ext lo64)

**Comment by ianjevans** [comment]
If you ran the app previously, the table already exists with the old schema with `int` as the PK type. Run `DROP TABLE accounts` in `bank` on your cluster from a SQL shell, and then you should be able to run the example with no errors.

**Comment by ianjevans** [comment]
There are two reasons for the change in PK type.

First, most of the other simple CRUD examples in the [docs](https://www.cockroachlabs.com/docs/stable/build-a-nodejs-app-with-cockroachdb.html) use UUIDs for the PK, so this is just keeping the schema consistent across drivers/languages.

Second, using an `int` as the PK type, especially a sequential integer, is an anti-pattern in a distributed database, as it creates hot ranges. So using UUIDs is a best practice.

**Comment by readytheory** [comment]
> If you ran the app previously, the table already exists with the old schema with `int` as the PK type. Run `DROP TABLE accounts` in `bank` on your cluster from a SQL shell, and then you should be able to run the example with no errors.

Thank you, and sorry for red herring.  Verified I was able to run the code with UUID after I dropped the table I created a couple days ago.

**Comment by readytheory** [comment]
issue resolved, user error
